# Generated by Django 4.2.11 on 2024-05-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_enrollment_course'),
        ('users', '0003_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, related_name='completed_by_students', to='courses.course'),
        ),
    ]
