# Generated by Django 4.2.11 on 2024-05-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment_enrollment_date_alter_course_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_count',
            field=models.IntegerField(default=0),
        ),
    ]
